# Generated by Django 3.2 on 2022-07-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(choices=[(1, 'Напитки'), (2, 'Выпечка')], on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foods.foodcategory', verbose_name='Раздел меню'),
        ),
    ]
