# Generated by Django 3.2 on 2022-07-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20220704_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foods.foodcategory', verbose_name='Раздел меню'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_publish',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
